[project]
name = "theodolite"
dependencies = [
	"numpy>=2.2,<3.0",
	"matplotlib>=3.9.0,<4.0",
]

[tool.maturin]
python-packages = ["theodolite"]
features = ["python"]

[build-system]
requires = ["maturin>=1.7.0,<2.0"]
build-backend = "maturin"
